# Generated by Django 4.1.1 on 2022-09-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonName', models.CharField(max_length=100)),
                ('sciName', models.CharField(max_length=100)),
                ('habitat', models.TextField(max_length=250)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
