# Generated by Django 4.1.1 on 2022-09-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('age', models.CharField(choices=[('L', 'Larval'), ('J', 'Juvenile'), ('S', 'Subadult'), ('A', 'Adult')], default='A', max_length=1)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.fish')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
